name: Load secrets from Dashlane
description: Inject secrets from your vault in a CI using the Dashlane CLI.
author: Dashlane
branding:
    icon: lock
    color: orange
runs:
    using: node20
    main: dist/index.js
