name: Load secrets from Dashlane
description: Makes it possible to inject secrets from your vault in a CI using the Dashlane CLI.
author: Dashlane
branding:
  icon: key
  color: grey
runs:
  using: node20
  main: dist/index.js
